# config/cloudinary.yml

---
development:
  cloud_name: hthevhqqv
  api_key: <%= ENV["CL_ID"] %>
  api_secret: <%= ENV["CL_KEY"] %>
  enhance_image_tag: true
  static_file_support: false
  secure: true
production:
  cloud_name: hthevhqqv
  api_key: <%= ENV["CL_ID"] %>
  api_secret: <%= ENV["CL_KEY"] %>
  enhance_image_tag: true
  static_file_support: true
  secure: true
test:
  cloud_name: hthevhqqv
  api_key: <%= ENV["CL_ID"] %>
  api_secret: <%= ENV["CL_KEY"] %>
  enhance_image_tag: true
  static_file_support: false