development:
  integration_id: "10048"
  integration_key: "c37f2682-f127-4a6c-8539-72c92ffb7478"

test:
  integration_id: "10048"
  integration_key: "c37f2682-f127-4a6c-8539-72c92ffb7478"

production:
  integration_id: <%= ENV["INTEGRATION_ID"] %>
  integration_key: <%= ENV["INTEGRATION_KEY"] %>